"""
Shared data for server tools.
"""

# Weather data (10 different scenarios)
WEATHER_DATA = [
    {"condition": "Sunny", "temp": 28, "humidity": 45, "description": "Perfect beach weather! ☀️"},
    {"condition": "Rainy", "temp": 18, "humidity": 85, "description": "Grab your umbrella! 🌧️"},
    {"condition": "Snowy", "temp": -5, "humidity": 70, "description": "Winter wonderland! ❄️"},
    {"condition": "Cloudy", "temp": 22, "humidity": 60, "description": "Overcast skies ahead ☁️"},
    {"condition": "Windy", "temp": 20, "humidity": 50, "description": "Hold onto your hat! 💨"},
    {"condition": "Foggy", "temp": 15, "humidity": 95, "description": "Visibility is low! 🌫️"},
    {"condition": "Stormy", "temp": 16, "humidity": 90, "description": "Thunder and lightning! ⛈️"},
    {"condition": "Hot", "temp": 35, "humidity": 40, "description": "Scorching hot day! 🔥"},
    {"condition": "Cold", "temp": 5, "humidity": 55, "description": "Bundle up! 🧊"},
    {"condition": "Misty", "temp": 12, "humidity": 88, "description": "Mysterious mist! 🌫️"},
]

# Food recommendations mapped to weather conditions
WEATHER_FOOD_MAP = {
    "Sunny": [
        {"food": "Ice Cream", "funny": "Because nothing says 'I'm melting' like ice cream on a sunny day! 🍦"},
        {"food": "Fresh Salad", "funny": "Light and refreshing - just like your chances of staying cool! 🥗"},
        {"food": "Cold Smoothie", "funny": "Blended perfection to beat the heat! 🥤"},
        {"food": "BBQ Burger", "funny": "Grill it while the sun's out! 🔥🍔"},
        {"food": "Watermelon", "funny": "Nature's air conditioner! 🍉"},
        {"food": "Fish Tacos", "funny": "Fresh catch for a hot day! 🌮🐟"},
        {"food": "Gazpacho", "funny": "Cold soup for hot heads! 🥣"},
        {"food": "Frozen Yogurt", "funny": "Cooler than your ex's heart! 🍧"},
        {"food": "Ceviche", "funny": "Citrusy and cool - like a beach vacation! 🦐"},
        {"food": "Popsicle", "funny": "Childhood memories in frozen form! 🍭"},
    ],
    "Rainy": [
        {"food": "Hot Soup", "funny": "Warm your soul while the rain soaks your shoes! 🍲"},
        {"food": "Grilled Cheese", "funny": "Comfort food for when the sky is crying! 🧀"},
        {"food": "Mac and Cheese", "funny": "Cheesy goodness to brighten a gloomy day! 🧀🍝"},
        {"food": "Chili", "funny": "Spicy warmth to fight the damp! 🌶️"},
        {"food": "Hot Chocolate", "funny": "Liquid happiness in a cup! ☕"},
        {"food": "Fried Chicken", "funny": "Crispy comfort for wet weather! 🍗"},
        {"food": "Ramen", "funny": "Steamy noodles for a steamy day! 🍜"},
        {"food": "Pot Pie", "funny": "Warm and cozy like a blanket! 🥧"},
        {"food": "Tea and Cookies", "funny": "British weather calls for British comfort! ☕🍪"},
        {"food": "Stew", "funny": "Hearty and warm - just like your grandma's hug! 🍲"},
    ],
    "Snowy": [
        {"food": "Hot Cocoa", "funny": "Marshmallows optional, warmth mandatory! ☕"},
        {"food": "Chili", "funny": "Spice up your frozen existence! 🌶️"},
        {"food": "Soup", "funny": "Liquid warmth for solid cold! 🍲"},
        {"food": "Hot Pot", "funny": "Communal warmth in a pot! 🍲"},
        {"food": "Roasted Chicken", "funny": "Hot bird for a cold day! 🍗"},
        {"food": "Lasagna", "funny": "Layered warmth for layered clothing! 🍝"},
        {"food": "Mulled Wine", "funny": "Warm wine for cold times! 🍷"},
        {"food": "Baked Potato", "funny": "Hot and starchy - nature's hand warmer! 🥔"},
        {"food": "Fondue", "funny": "Melted cheese for melted snow! 🧀"},
        {"food": "Goulash", "funny": "Eastern European warmth! 🍲"},
    ],
    "Cloudy": [
        {"food": "Sandwich", "funny": "Simple food for simple skies! 🥪"},
        {"food": "Pasta", "funny": "Carbs to match the cloud cover! 🍝"},
        {"food": "Pizza", "funny": "Round food for round clouds! 🍕"},
        {"food": "Burrito", "funny": "Wrapped comfort for overcast days! 🌯"},
        {"food": "Sushi", "funny": "Fresh fish for fresh air! 🍣"},
        {"food": "Quesadilla", "funny": "Cheesy triangles for cloudy triangles! 🧀🌯"},
        {"food": "Stir Fry", "funny": "Quick and easy - like the clouds! 🍳"},
        {"food": "Fried Rice", "funny": "Classic comfort for classic clouds! 🍚"},
        {"food": "Tacos", "funny": "Taco 'bout cloudy weather! 🌮"},
        {"food": "Nachos", "funny": "Crispy chips for crispy clouds! 🧀"},
    ],
    "Windy": [
        {"food": "Panini", "funny": "Pressed sandwich for windy pressure! 🥪"},
        {"food": "Wrap", "funny": "Wrapped tight against the wind! 🌯"},
        {"food": "Soup", "funny": "Steamy bowl to warm the breeze! 🍲"},
        {"food": "Hot Dog", "funny": "Classic wind-resistant food! 🌭"},
        {"food": "Burger", "funny": "Hold on tight! 🍔"},
        {"food": "Fries", "funny": "Crispy sticks for a breezy day! 🍟"},
        {"food": "Chili", "funny": "Spicy warmth to fight the wind! 🌶️"},
        {"food": "Stew", "funny": "Hearty meal for a gusty day! 🍲"},
        {"food": "Chowder", "funny": "Creamy comfort for windy weather! 🍲"},
        {"food": "Curry", "funny": "Spicy and warming! 🍛"},
    ],
    "Foggy": [
        {"food": "Soup", "funny": "Warm bowl to cut through the fog! 🍲"},
        {"food": "Stew", "funny": "Hearty meal for mysterious weather! 🍲"},
        {"food": "Hot Chocolate", "funny": "Warm drink for a foggy day! ☕"},
        {"food": "Porridge", "funny": "Comforting and warm! 🥣"},
        {"food": "Congee", "funny": "Simple and soothing! 🍲"},
        {"food": "Risotto", "funny": "Creamy comfort for low visibility! 🍚"},
        {"food": "Mac and Cheese", "funny": "Cheesy goodness to brighten the fog! 🧀🍝"},
        {"food": "Hot Pot", "funny": "Steamy meal for a steamy day! 🍲"},
        {"food": "Pho", "funny": "Steamy broth to clear the fog! 🍜"},
        {"food": "Ramen", "funny": "Warm noodles for a misty day! 🍜"},
    ],
    "Stormy": [
        {"food": "Comfort Food", "funny": "Any warm meal to ride out the storm! 🍲"},
        {"food": "Soup", "funny": "Warm bowl to weather the storm! 🍲"},
        {"food": "Stew", "funny": "Hearty meal for stormy weather! 🍲"},
        {"food": "Casserole", "funny": "Baked comfort for a storm! 🥘"},
        {"food": "Chili", "funny": "Spicy warmth during the storm! 🌶️"},
        {"food": "Lasagna", "funny": "Layered comfort for layered storms! 🍝"},
        {"food": "Pot Pie", "funny": "Cozy pie for a stormy day! 🥧"},
        {"food": "Shepherd's Pie", "funny": "Comforting pie for the storm! 🥧"},
        {"food": "Mac and Cheese", "funny": "Cheesy comfort during the storm! 🧀🍝"},
        {"food": "Hot Chocolate", "funny": "Warm drink to calm the storm! ☕"},
    ],
    "Hot": [
        {"food": "Ice Cream", "funny": "Cool down with ice cream! 🍦"},
        {"food": "Cold Smoothie", "funny": "Blended refreshment! 🥤"},
        {"food": "Frozen Yogurt", "funny": "Cool and creamy! 🍧"},
        {"food": "Watermelon", "funny": "Nature's coolant! 🍉"},
        {"food": "Salad", "funny": "Light and refreshing! 🥗"},
        {"food": "Gazpacho", "funny": "Cold soup for hot days! 🥣"},
        {"food": "Ceviche", "funny": "Citrusy and cool! 🦐"},
        {"food": "Popsicle", "funny": "Frozen treat! 🍭"},
        {"food": "Cold Noodles", "funny": "Chilled noodles for heat! 🍜"},
        {"food": "Fruit Salad", "funny": "Fresh and fruity! 🍓"},
    ],
    "Cold": [
        {"food": "Hot Soup", "funny": "Warm your bones! 🍲"},
        {"food": "Hot Chocolate", "funny": "Liquid warmth! ☕"},
        {"food": "Stew", "funny": "Hearty warmth! 🍲"},
        {"food": "Hot Pot", "funny": "Communal warmth! 🍲"},
        {"food": "Chili", "funny": "Spicy heat! 🌶️"},
        {"food": "Roasted Meat", "funny": "Hot protein for cold days! 🍗"},
        {"food": "Casserole", "funny": "Baked warmth! 🥘"},
        {"food": "Lasagna", "funny": "Layered heat! 🍝"},
        {"food": "Pot Pie", "funny": "Warm and cozy! 🥧"},
        {"food": "Mulled Wine", "funny": "Warm wine for cold times! 🍷"},
    ],
    "Misty": [
        {"food": "Soup", "funny": "Warm bowl for misty weather! 🍲"},
        {"food": "Stew", "funny": "Hearty meal for mysterious mist! 🍲"},
        {"food": "Hot Chocolate", "funny": "Warm drink for a misty day! ☕"},
        {"food": "Porridge", "funny": "Comforting warmth! 🥣"},
        {"food": "Risotto", "funny": "Creamy comfort! 🍚"},
        {"food": "Mac and Cheese", "funny": "Cheesy goodness! 🧀🍝"},
        {"food": "Hot Pot", "funny": "Steamy meal! 🍲"},
        {"food": "Pho", "funny": "Steamy broth! 🍜"},
        {"food": "Ramen", "funny": "Warm noodles! 🍜"},
        {"food": "Congee", "funny": "Simple and warm! 🍲"},
    ],
}
